### PR TITLE
Added Tests Using RSpec Gem

### PR DESCRIPTION
**Pull request by MarilenaRoque**
## RSpec Testing :rocket: 

On this branch we have developed tests to our version of the enumerable methods from Ruby. On this tests we're checking if:

### my_each

- It returns enum if the block is given
- It returns an enumerator if no block is given

### my_each_with_index

- It returns an enumerator if no block is given
- Run the correct task when a block is given

### my_select

- It returns an enumerator if no block is given
- Return the correct array when called by an array
- Return the correct array when called by a range

### my_all

- Returns true if all the elements are even
- Return false when no block is given and there are false elements

### my_any

- Returns true because one of the elements is even
- Return false because none of the elements are true and no block was given
- Testing if returns true when just a pattern is given
- Don't return true because none of the elements are true and no block was given

### my_none

- Return false when every element is true and no block is given
- Return true when every element returns false and a block is given
- Return true when every element returns false for a class pattern

### my_count

- Returns the number of strings equal a pattern given inside an array
- Returns the number of elements when no pattern or block is given inside an array
- Returns the number of strings inside the array

### my_map
- Return a new array modify by the block condition
- Return a new array from a range modify by the block condition
- Fill a new array with the element given in the block with the same length of the original one

### my_inject

- Returns the sum of every element inside an array, using a symbol argument
- Returns the sum every element inside an array plus 10, using a symbol and an initial value as arguments
- Returns the sum every element twice inside an array using a block
- Returns the longest word inside an array

### multiply_els

- Returns all elements of the array multiplied receiving the array as argument
- Returns all elements of the range multiplied receiving a range as an argument

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey Team :wave:
-
You have done a splendid job! :tada: I love how clean and modular your code is. Keep it up.
##
- Good job testing all the scenarios in all of the methods that were required of this project. 
- Just one more thing before we close this up. 

- [ ] Kindly ensure linter is configured properly and working and all checks to your files are passing. That's about it for this one. 
#
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by MarilenaRoque** [comment]
Thank you for the review @christianotieno!

- [x]  Linter is configured properly and working and all checks to your files are passing.

**Review by santiago-dev96 — APPROVED** [review]
# Project approved! :100:

Great work! I really like the way this team writes code! Everything is neatly organized and I appreciate that being a code reviewer. You also did a good job fixing the linter issues pointed out by the previous TSE. I wish you the best in your next projects, happy coding! :wave:

**Comment by MarilenaRoque** [comment]
Thank you so much @santiago-rodrig. I appreciate your review! :+1:

**Pull request merged**
